backend:
  name: github
  repo: gikere/michael-portfolio
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: "https://gikere.netlify.app"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "author", label: "Author", widget: "string", default: "Michael Ndung'u" }
      - { name: "cover", label: "Cover Image", widget: "image" }
      - { name: "slug", label: "Slug", widget: "string" }
      - { name: "categories", label: "Categories", widget: "list", default: ["General"] }
      - { name: "body", label: "Body", widget: "markdown" }
